version: "3"
services:
  auth_service:
    build: AuthService
    restart: always
    ports:
      - "3000:80"
    links:
      - mongo_db
  post_service:
    build: PostService
    restart: always
    ports:
      - "4000:80"
    links:
      - mongo_db
  comment_service:
    build: CommentService
    restart: always
    ports:
      - "5000:80"
      - "9090:9090"
    links:
      - mongo_db
  mongo_db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    logging:
      driver: none
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    logging:
      driver: none
