version: "3"
services:
  auth_service:
    build: AuthService
    restart: always
    environment:
      DB_HOST: mongo_db
      DB_DBNAME: "auth_service"
      DB_PORT: "27017"
      PORT: "80"
      JWT_SECRET_KEY: "example_secret_key"
      RABBIT_MQ_HOST: "rabbitmq"
    ports:
      - "3000:80"
    links:
      - mongo_db
  post_service:
    build: PostService
    restart: always
    environment:
      DB_HOST: mysql_db
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_DBNAME: "post_service"
      JWT_SECRET_KEY: "example_secret_key"
    ports:
      - "4000:4000"
    links:
      - mysql_db
  comment_service:
    build: CommentService
    restart: always
    environment:
      DB_HOST: mysql_db
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_DBNAME: "comment_service"
      JWT_SECRET_KEY: "example_secret_key"
    ports:
      - "5000:5000"
    links:
      - mysql_db
  mongo_db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    logging:
      driver: none
  mysql_db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: post_service
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3308:3306"
    logging:
      driver: none
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    logging:
      driver: none
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql_db:db
    ports:
      - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: password
    logging:
      driver: none