version: "3"
services:
  auth_service:
    build: AuthService
    restart: always
    environment:
      DB_HOST: mongo_db
      DB_DATABASE: "auth_service"
      DB_PORT: "27017"
      PORT: "3000"
      JWT_STRING_KEY: "mY69VjXlZm8vCrdd"
    ports:
      - "3000:3000"
    links:
      - mongo_db
  mongo_db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    logging:
      driver: none