version: "3"
services:
  auth_service:
    build: AuthService
    restart: always
    environment:
      DB_HOST: mongo_db
      DB_PORT: "27017"
      DB_DBNAME: "auth_service"
      JWT_SECRET_KEY: "example_secret_key"
      RABBIT_MQ_HOST: "rabbitmq"
      PORT: "80"
    ports:
      - "3000:80"
    links:
      - mongo_db
  post_service:
    build: PostService
    restart: always
    environment:
      DB_HOST: mongo_db
      DB_PORT: "27017"
      DB_DBNAME: "post_service"
      JWT_SECRET_KEY: "example_secret_key"
      RABBIT_MQ_HOST: "rabbitmq"
      PORT: "80"
      GRPC_HOST: "comment_service"
      GRPC_PORT: "9090"
    ports:
      - "4000:80"
    links:
      - mongo_db
  comment_service:
    build: CommentService
    restart: always
    environment:
      DB_HOST: mongo_db
      DB_PORT: "27017"
      DB_DBNAME: "comment_service"
      JWT_SECRET_KEY: "example_secret_key"
      RABBIT_MQ_HOST: "rabbitmq"
      PORT: "80"
      GRPC_PORT: "9090"
    ports:
      - "5000:80"
      - "9090:9090"
    links:
      - mongo_db
  mongo_db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    logging:
      driver: none
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    logging:
      driver: none
